name: CI Build
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - arch: amd64
            runner_label: ubuntu-24.04
          - arch: arm64
            runner_label: ubuntu-24.04-arm
            
    runs-on: ${{ matrix.runner_label }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.0
        with:
          cosign-release: 'v2.2.3'

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.23.0

      - name: Install sbomlyze
        run: |
          set -e
          mkdir -p /tmp/bin
          curl -sSfL https://raw.githubusercontent.com/rezmoss/sbomlyze/main/install.sh -b ./tmp/bin | sh -x
          ls -l ./bin
          sudo mv /tmp/bin/sbomlyze /usr/bin

      - name: build containers if changed
        uses: kfox1111/container-build-and-refresh-action@main
        with:
          repo: ghcr.io/kfox1111/testing-repo
