jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner_label: ubuntu-24.04
          - arch: arm64
            runner_label: ubuntu-24.04-arm
            
    runs-on: ${{ matrix.runner_label }}

    steps:
      - uses: actions/checkout@v4
      
      - name: build containers if changed
        uses: kfox1111/container-build-and-refresh-action@main
